Feature/js 1
slver-dragon/JS pull request #1
Opened 2021-06-03 11:05 UTC by slver-dragon

2021-06-03 14:14 UTC, DenisKalyanov requested changes

2021-06-03 14:14 UTC, DenisKalyanov commented on scripts/script.js
> +  pos > 375 ? elementReplace(0) : elementReplace(pos + 75);
375, 75 что это за цифры?

2021-06-03 14:14 UTC, DenisKalyanov commented on scripts/script.js
> +  pos < 75 ? elementReplace(450) : elementReplace(pos - 75);
что ты хранишь в  pos? если это начальная позиция какого-то твоего блока, то наверно у его и так есть начальная позиция elem.style.left = 0;

2021-06-03 14:14 UTC, DenisKalyanov commented on scripts/script.js
> +    targetRadio = event.target.id}
Ты сначала создаёшь переменную, сохраняешь в неё элемент на котором произошло действие. А потом в этот элемент пресохраняешь его id. Просто зачем? 

Может сразу внутри описать код с 21 строки. Без перезаписи переменной

2021-06-03 16:05 UTC, slver-dragon commented on index.html
> +          id="slider-picture"
Виноват, размножал строку и не почистил id. Удалил.

2021-06-03 16:07 UTC, slver-dragon commented on scripts/script.js
> +  pos < 75 ? elementReplace(450) : elementReplace(pos - 75);
В pos хранится текущее положение слайда относительно комплекта слайдов.

2021-06-03 16:15 UTC, slver-dragon commented on scripts/script.js
> +    targetRadio = event.target.id}
Я использую одну переменную и для контроля и верного выбора узла, и в дальнейшего "вытягивания" номера слайда.  Хотя в дальнейшем буду искать вариант иной обработки, в связи с различными размерами слайдов.

2021-06-03 16:17 UTC, slver-dragon commented on scripts/script.js
> +  pos > 375 ? elementReplace(0) : elementReplace(pos + 75);
Это размеры в пикселях, которые ниже передаются в стиль.

2021-06-09 12:08 UTC, DenisKalyanov requested changes

2021-06-09 12:08 UTC, DenisKalyanov commented on scripts/script.js
> +  let targetRadio = event.target.tagName;
Зачем вообще выполнять функцию если он не span?

2021-06-09 12:08 UTC, DenisKalyanov commented on scripts/script.js
> +  }
32 line: elementNum == 0
35 line: if (elementNum == 0) {
Ты проверяешь одно и тоже условие

2021-06-09 12:08 UTC, DenisKalyanov commented on scripts/script.js
> +  if (elementNum - 1 == slideCount) {
elementNum == slideCount.length

2021-06-09 12:08 UTC, DenisKalyanov commented on scripts/script.js
> +let elementPrev;
неплохо было бы избавиться от некоторых переменных. Их очень много. 
Например let slideCount = 7; это количество чего, слайдов. Чем это не универсально. меняя кол-во картинок, тебе каждый раз придется менять эту переменную. Сразу бы получать её исходя из кол-во картинок.

2021-06-09 12:08 UTC, DenisKalyanov commented on scripts/script.js
> +  sliderLister.style.width = elementNext.naturalWidth + "px";
что такое Lister?

2021-06-09 12:47 UTC, slver-dragon commented on css/style.css
> +  flex-direction: row;
Я подумал что будет наследоваться вертикальная группировка из body. Вот и перестраховался. Убрал.

2021-06-09 13:20 UTC, slver-dragon commented on index.html
> +      <button class="element-back" id="element-back">&lt;</button>
Переделал.

2021-06-09 13:20 UTC, slver-dragon commented on index.html
> +    <div class="slider-choise" id="slider-choise"></div>
Переделал на querySelector.

2021-06-09 13:22 UTC, slver-dragon commented on scripts/script.js
> +  }*/
Я уже это почистил. Не знаю почему сохранилось.

2021-06-09 13:23 UTC, slver-dragon commented on scripts/script.js
> +    rowWidthPx = rowWidthPx + elementTek.naturalWidth;
Спасибо, забыл про это.

2021-06-09 13:39 UTC, slver-dragon commented on scripts/script.js
> +    elementTek.style.width = elementTek.naturalWidth + "px";
Согласен, тоже перестраховался, поскольку без дополнительного указания высоты все слетает. Удалил лишнее.

2021-06-09 14:31 UTC, slver-dragon commented on scripts/script.js
> +      '.png" alt=""/>';
Уже переделал. Спасибо за подсказку!

2021-06-09 14:48 UTC, slver-dragon commented on scripts/script.js
> +});
В данной функции я выбираю смещение для соответствующего элемента и на него перемещаю "окно"

2021-06-09 15:47 UTC, slver-dragon commented on scripts/script.js
> +  }
Согласен, не доглядел. Переделывая по аналогии с движением в другую сторону отдельно делал проверку и упустил этот момент. Поправил и объединил.

2021-06-09 16:12 UTC, slver-dragon commented on scripts/script.js
> +let elementPrev;
Убрал две переменные, которые после последних изменений использовались только по 1 разу. С остальными сложнее. Разноразмерные картинки требуют больше переменных, чем однородные, в которых некоторые значения можно просто вычислять перемножением.

2021-06-09 16:22 UTC, slver-dragon commented on scripts/script.js
> +  sliderLister.style.width = elementNext.naturalWidth + "px";
Lister - вроде окошечка в котором показывается текущая картинка.

2021-06-09 17:39 UTC, slver-dragon commented on index.html
> +  <body onload="initialization ()">
Попробовал, возникла еще одна проблема. В этой функции рассчитывается длина всех картинок. По этой причине нужно импортировать ее в другой скрипт. Судя по всему решить можно создав пространство имен, но как его создать не совсем представляю.

2021-06-09 18:55 UTC, slver-dragon commented on scripts/script.js
> +  let targetRadio = event.target.tagName;
Так я и не выполняю. Если не span, я выхожу из нее.

2021-06-11 10:23 UTC, slver-dragon commented on index.html
> +  <body onload="initialization ()">
Убрал из body вызов инициализации. Сделал вызов в самом скрипте.

2021-06-11 10:25 UTC, slver-dragon commented on scripts/script.js
> +    sliderChoise.insertAdjacentHTML("afterbegin", element);
Сменил именование на slider-marker.

2021-06-17 16:33 UTC, merged